[workspace]
members = [
    "cryshub_rs",
    "crypdash_rs",
    "nonce_relation_rs",
    "address_analyzer_rs",
    "bias_detector_rs",
    "lattice_attack_rs",
    "cryscout_worker_rs",
    "bleichenbacher_fourier",
    "wallet_scout_rs"
, "kangaroo_rs", "physics_engine_rs", "genotype_rs", "neural_scout_rs"]
resolver = "2"
